### ISSUE TITLE
npm install fails on semantic-release 

### ISSUE THREAD

**Issue by igalic** [hoodiehq/hapi-couchdb-store#6]
when running npm install on a freshly cloned hapi-couchdb-store, i'm getting the following error:

```
igalic@levix ~/s/r/hapi-couchdb-store (master=)>  npm install 
npm WARN engine semantic-release@4.1.0: wanted: {"node":">=0.10","npm":">=2"} (current: {"node":"0.10.40","npm":"1.4.28"})
npm ERR! 404 Not Found
npm ERR! not ok code 0
igalic@levix ~/s/r/hapi-couchdb-store (master=) [1]>
```

see this gist for the --verbose output https://gist.github.com/igalic/9138b47683482fff0581

**Comment by boennemann** [comment]
The dependency semantic-release requires npm@^2 to be installed.
Running `npm install --global npm` and then `npm install` again should fix this problem.

Best,
Stephan
